### ISSUE TITLE
Missing property and improvement suggestions

### ISSUE THREAD

**Issue by Mr-KayJayDee** [Androz2091/insta.js#15]
Missing property: 

- [x] message.author.followerCount
- [x] message.author.biography
- [x] message.author.followingCount
- [x] message.author.isBusiness
- [x] message.author.mediaCount
- [x] message.author.totalIgtvVideos

Improvement: 

- [x] When a user like a message the messageCreate event is emitted, maybe a messageLikeAdd (and messageLikeRemove) or smth else should be good.

Things that summons errors:

- [x] When an user sends an file the message property is undefined
- [ ] When an user answer a story the message property is undefined
- [x] When a call is started it shows a message in a chat and this message is undefined
- [x] When the group name is edited it shows a message in a chat and this message is undefined
- [x] When a heart (default instagram heart) or a sticker is received the message property is undefined
- [x] When an user send a voice message the message property is undefined

Feature ideas: 

- [x] userAdded (a user has been added to the group)
- [x] userRemoved (a user has been removed from the group, maybe we can know if he was kicked or just has left)
- [x] groupUserOpped (a user has been given the admin permissions)
- [ ] groupChatEnded (a group chat has been ended)
- [ ] groupChatCreated (a group chat has been created, this will maybe emit a userAdded event)
- [x] groupNameUpdate (the group name has been changed)

Maybe i will edit it if i have new suggestions.

**Comment by Androz2091** [comment]
> Missing property:

 > message.author.followerCount
 message.author.biography
 message.author.followingCount
 message.author.isBusiness
 message.author.mediaCount
 message.author.totalIgtvVideos

These properties can now be retrieved using something like: 
```js
client.on('messageCreate', async (message) => {

    // fetch the user if it hasn't already be done 
    if (!message.author.followerCount) await message.author.fetch();

});
```
