### ISSUE TITLE
Détecter un utilisateur qui arrête de nous suivre

### ISSUE THREAD

**Issue by ZerioDev** [Androz2091/insta.js#47]
Bonsoir Androz 👋

Je viens de parcourir la documentation mais je n'ai trouvé aucun moyen pour vérifier avec les évents si un utilisateur quelconque viens d'arrêter de nous suivre.

Est ce possible ? Ou alors est ce prévu ?

Bonne fin de soirée.

**Comment by Androz2091** [comment]
Salut :wave:

Non, cela n'est actuellement pas possible. Le principe de la librairie est d'écouter les notifications Instagram envoyées à ton compte (les mêmes que celle que tu recevrais sur ton téléphone), et Instagram n'envoie pas de notifications lorsqu'un compte se désabonne.

Il y a tout de même une solution qui marche plutôt bien. La librairie dispose d'une fonction qui récupère les abonnés d'un compte. Tu peux faire une boucle qui toutes les 30 secondes récupères les nouveaux abonnés et compare avec les anciens (et s'il y a un nouvel élément dans le tableau, c'est un nouvel abonné).
