### ISSUE TITLE
How To Send Message To Specific Username

### ISSUE THREAD

**Issue by Allviyan** [Androz2091/insta.js#50]
How To Send Message To Specific Username ?
where code example

**Comment by dcts** [comment]
You can get the `ig` instance (from `instagram-private-api`) and the use the following code:
```js
const Insta = require('@androz2091/insta.js');
const client = new Insta.Client();

await client.login(username, password);

// ensure the client is logged in
if (client.user === null) {
  throw new Error("client not logged in, please log in first");
}

// get instagramId of target user
const handle = "targetUserHandle";
const targetUserPk = await client.ig.user.getIdByUsername(handle);

// send DM to user
const targetDirectThread = client.ig.entity.directThread([targetUserPk]);
const result = await targetDirectThread.broadcastText("hello world from bot");
```

References for these methods can be found in the instagram-private-api repo:
- [getIdByUsername](https://github.com/dilame/instagram-private-api/blob/bbf7934b82ff11d1fb598fee6ee90c74ee797c69/src/repositories/user.repository.ts#L94)
- [broadcastText](https://github.com/dilame/instagram-private-api/blob/bbf7934b82ff11d1fb598fee6ee90c74ee797c69/src/entities/direct-thread.entity.ts#L33)


If you only need to send DMs without listening to incoming messages you can do this solely with the [`instagram-private-api`](https://github.com/dilame/instagram-private-api/). 

If you want to respond to incoming messages see the [instaJS basic example](https://github.com/Androz2091/insta.js#example).

Hope that helps.

**Comment by Androz2091** [comment]
Thank you for your answer,  but you can still use:
```js
client.fetchUser('davidguetta').then((user) => user.chat.send('hello'));
```
