### ISSUE TITLE
How can I get the username of the user who sent the message?

### ISSUE THREAD

**Issue by meseven** [Androz2091/insta.js#56]
Hi all,

If "message.author.id" and "client.user.id" are the same, I cannot get to which user the message was sent.

```javascript

client.on('messageCreate', (message) => {
  console.log(message.to_username) // ??
});
```

**Comment by Androz2091** [comment]
Hello :wave:

> If "message.author.id" and "client.user.id" are the same

They are not.
You can use the following:

```js
client.on('messageCreate', async (message) => {
	const author = message.author || await client.fetchUser(message.authorID);
	console.log(author); // the user object
});
```

**Comment by meseven** [comment]
I can always get the name of the author correctly. However, the username that receives the message is always the same as the client username.

```javascript
client.on('messageCreate', async (message) => {
  const author = message.author || (await client.fetchUser(message.authorID));
  console.table([
    {
      from: author.username, // correct always
      to: message.client.user.username,  // always same as client username
    },
  ]);
});
```

If it is an incoming message, there is no problem. However, the outgoing message "from" and "to" are always the same as the client username. How can I refactor "to" field?

**Comment by Androz2091** [comment]
Yes it is always the same because the message is sent by the client. You can just ignore the messages sent by yourself using ```js
if(message.authorID === client.user.id) return;
```

**Comment by Ayoub-k** [comment]
hi All, how i can send message with chat.sendMessage('Hey!');

**Comment by Androz2091** [comment]
please open another issue - this is not related to the original question
